> ### **Assignment 2 - Numpy Array Operations** 
>


Write a short introduction about Numpy and list the chosen functions. 

function1 = np.append 

function2 = np.average

function3 = np.arange

function4 = np.squeeze

function5 = np.vstack




In [1]:
import numpy as np

## Function 1 - np.append
np.append function add elements to the end of an array provided that the dimensions of the elements should be same.

In [2]:
# Example 1 - working (change this)
arr1 = [1, 2, 1, 25, 26]
np.append(arr1, [24, 23, 15])


array([ 1,  2,  1, 25, 26, 24, 23, 15])

We can put lists as an element inside the array, then append it with the expected lists or any element regardless of their size.



In [4]:
# Example 2 - working
arr2 = [[2, 4, 5], [6, 7, 8]]
np.append(arr2, [10, 12])
np.append(arr2, [10, 12, 13, 14])

array([ 2,  4,  5,  6,  7,  8, 10, 12, 13, 14])

When axis is specified, arrays must have the same shape.

In [3]:
# Example 3 - breaking (to illustrate when it breaks)
arr3 = [[2, 4, 5], [6, 7, 8]]
np.append(arr3, [14, 15, 16], axis = 0)

ValueError: all the input arrays must have same number of dimensions, but the array at index 0 has 2 dimension(s) and the array at index 1 has 1 dimension(s)

ValueError: all the input arrays must have same number of dimensions, but the array at index 0 has 2 dimension(s) and the array at index 1 has 1 dimension(s)

Some closing comments about when to use this function.

In [4]:
# Fix
arr3 = [[2, 4, 5], [6, 7, 8]]
np.append(arr3, [[14, 15, 16], [12, 15, 16]], axis = 0)

array([[ 2,  4,  5],
       [ 6,  7,  8],
       [14, 15, 16],
       [12, 15, 16]])

In arr3, index 0 has 2 dimensions, while the element to be appended has 1 dimension, thus breaks down. To fix this, the element to be appended should have 2 dimensions as well.

## Function 2 - np.average

Add some explanations

In [5]:
# Example 1 - working
arr33 = [[2, 4, 5], [6, 7, 8], [7, 8, 9]]
np.average(arr33)

6.222222222222222

Explanation about example

In [6]:
#Example 2 -working
arr11 = [1, 2, 1, 25, 26]
np.average(arr11)

11.0

Explanation about example

In [7]:
# Example 3 - breaking (to illustrate when it breaks)
a = [-1, 1, 2, 2]
np.average(a,[1,2,3,4], axis=0)

TypeError: _average_dispatcher() got multiple values for argument 'axis'

Explanation about example (why it breaks and how to fix it)

In [16]:
a = [-1, 1, 2, 2]
np.average(a)

1.0

Some closing comments about when to use this function.

## Function 3 - np.arange

Add some explanations

In [11]:
# Example 1 - working
np.arange(3,7)

array([3, 4, 5, 6])

Explanation about example

In [17]:
# Example 2 - working
np.arange(3,7,2)

array([3, 5])

Explanation about example

In [19]:
# Example 3 - breaking (to illustrate when it breaks)
np.arange(3,7,int)

TypeError: unsupported operand type(s) for /: 'int' and 'type'

Explanation about example (why it breaks and how to fix it)

In [ ]:
np.arange(3,7,2,int)

Some closing comments about when to use this function.

## Function 4 - np.squeeze

Add some explanations

In [41]:
# Example 1 - working
x = np.array([[[0], [1], [2]]])
x.shape


(1, 3, 1)

In [42]:
np.squeeze(x,axis=0).shape

(3, 1)

Explanation about example

In [51]:
# Example 2 - working
x1 = np.array([[[0], [1], [2]]])
x1


array([[[0],
        [1],
        [2]]])

In [52]:
np.squeeze(x1,axis=1).shape

ValueError: cannot select an axis to squeeze out which has size not equal to one

Explanation about example

In [29]:
# Example 3 - breaking (to illustrate when it breaks)
x11 = np.array([[[0], [1], [2]]])
x11.shape

(1, 3, 1)

In [44]:
np.squeeze(x11,axis=1).shape

NameError: name 'x11' is not defined

Explanation about example (why it breaks and how to fix it)

Some closing comments about when to use this function.

## Function 5 - np.vstack

Add some explanations

In [54]:
# Example 1 - working
x = np.array([3, 5, 7])
y = np.array([5, 7, 9])
np.vstack((x,y))

array([[3, 5, 7],
       [5, 7, 9]])

Explanation about example

In [57]:
# Example 2 - working
x = np.array([[3], [5], [7]])
y = np.array([[5], [7], [9]])
np.vstack((x,y))

array([[3],
       [5],
       [7],
       [5],
       [7],
       [9]])

Explanation about example

In [59]:
# Example 3 - breaking (to illustrate when it breaks)
x1 = np.array([[3], [5], [7]])
y1 = np.array([5], [7], [9])
np.vstack((x1,y1))

TypeError: array() takes from 1 to 2 positional arguments but 3 were given

Explanation about example (why it breaks and how to fix it)

In [60]:
x1 = np.array([[3], [5], [7]])
y1 = np.array([[5], [7], [9]])
np.vstack((x1,y1))

array([[3],
       [5],
       [7],
       [5],
       [7],
       [9]])

Some closing comments about when to use this function.

In [1]:
import numpy as np
import pandas as pd



In [2]:
#create DataFrame with some NaN values
df = pd.DataFrame({'rating': [np.nan, 85, np.nan, 88, 94, 90, 76, 75, 87, 86],
                   'points': [25, np.nan, 14, 16, 27, 20, 12, 15, 14, 19],
                   'assists': [5, 7, 7, np.nan, 5, 7, 6, 9, 9, 5],
                   'rebounds': [11, 8, 10, 6, 6, 9, 6, 10, 10, 7]})


In [3]:
df

rating  points  assists  rebounds
0     NaN    25.0      5.0        11
1    85.0     NaN      7.0         8
2     NaN    14.0      7.0        10
3    88.0    16.0      NaN         6
4    94.0    27.0      5.0         6
5    90.0    20.0      7.0         9
6    76.0    12.0      6.0         6
7    75.0    15.0      9.0        10
8    87.0    14.0      9.0        10
9    86.0    19.0      5.0         7

In [8]:
df['rating'].median()

86.5

In [9]:
df['rating'] = df['rating'].fillna(df['rating'].median())


In [10]:
df

rating  points  assists  rebounds
0    86.5    25.0      5.0        11
1    85.0     NaN      7.0         8
2    86.5    14.0      7.0        10
3    88.0    16.0      NaN         6
4    94.0    27.0      5.0         6
5    90.0    20.0      7.0         9
6    76.0    12.0      6.0         6
7    75.0    15.0      9.0        10
8    87.0    14.0      9.0        10
9    86.0    19.0      5.0         7